// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbjrygaicabqlacnrksy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRianJ5Z2FpY2FicWxhY25ya3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjY3MzEsImV4cCI6MjA2NTUwMjczMX0.C4vEXhrnFhYJ9c-zB_v9t9LSBlqVV2SR9iT42QfW8tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);